version: "3.9"

services:
  db:
    image: postgres:16
    container_name: trainer-db
    environment:
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: trainer
      POSTGRES_DB: trainerdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  # api:
  #   build:
  #     context: ./apps/api
  #     dockerfile: Dockerfile
  #   container_name: trainer-api
  #   env_file:
  #     - ./apps/api/.env
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"

  # web:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile
  #   container_name: trainer-web
  #   depends_on:
  #     - api
  #   ports:
  #     - "5173:80"

volumes:
  db-data:
