apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitflow-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Gidraff/trainer-dash.git'
    targetRevision: main
    path: k8s/overlays/production # This points to your Kustomize setup
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # The namespace where the API will run
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true