apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# ArgoCD monitors this specific block:
images:
- name: fitflow-api
  newTag: 8d15d4be9d476feebf6e9b307221e21b39dc5b59
