apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# ArgoCD monitors this specific block:
images:
- name: fitflow-api
  newName: us-central1-docker.pkg.dev/gidraff-cloudkite-58sdk3/fitflow/api
  newTag: 61952a27d2f77f3923a15c945cc433353fa0a2b7
