apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml

# ArgoCD monitors this specific block:
images:
  - name: fitflow-api
    newName: us-central1-docker.pkg.dev/gidraff-cloudkite-58sdk3/fitflow/api
    newTag: "v1.0.0" # CI will update this line automatically