apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# ArgoCD monitors this specific block:
images:
- name: fitflow-api
  newName: us-central1-docker.pkg.dev/gidraff-cloudkite-58sdk3/fitflow/api
  newTag: a77dd1f29df76671b95a45c42cb574e8213b0c6e
